### ISSUE TITLE
Support ergonomic merging styles into child components

### ISSUE THREAD

**Issue by JAStanton** [convoyinc/dapper#43]
```js
const STYLES = dapper.compile({
  root: {
    position: 'relative',
  },
  child: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
});

class Parent extends Component {
  
  styles = dapper.reactTo(this, STYLES);

  render() {
    return (
      <div className={this.styles.root}>
        <Child className={this.styles.child} />
      </div>
    );
  }
}

const STYLES2 = dapper.compile({
  root: {
    color: 'red',
  },
});

class Child extends Component {

   styles = dapper.reactTo(this, STYLES2);

  render() {
    return (
      <div className={this.styles.root} />
    );
  }

}
```

I would expect `Child` styles to compile to:

```css
.dapper-child-a {
  color: 'red',
  position: 'absolute',
  top: 0,
  left: 0,
}

```
